### ISSUE TITLE
运行gen_instance_info.py的时候报错

### ISSUE THREAD

**Issue by JYounngS** [MCG-NJU/SparseOcc#53]
Traceback (most recent call last):
  File "/data2/sjy/miniconda3/envs/sparseocc/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "gen_instance_info.py", line 82, in process_add_instance_info
    occ_gt_path = token2path[sample['token']]
KeyError: 'e93e98b63d3b40209056d129dc53ceee'

**Comment by YANG-CY-163** [comment]
This error is usually caused by the wrong gt_root, you can check if the `gt_path` is correct and if the dict `token2path` is empty
![image](https://github.com/user-attachments/assets/a39ce928-0368-46b5-b970-689eee963cea)

**Comment by JYounngS** [comment]
Thanks a lot. I have solved it out !
